# Generated by Django 3.1.7 on 2021-03-22 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleek', '0002_person_favorite_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.ForeignKey(default='Tulsa', on_delete=django.db.models.deletion.CASCADE, to='fleek.city'),
            preserve_default=False,
        ),
    ]
