# Generated by Django 3.1.7 on 2021-03-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleek', '0003_auto_20210322_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
    ]
