# Generated by Django 3.1.7 on 2021-03-22 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleek', '0004_remove_person_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fleek.city'),
        ),
    ]
