# Generated by Django 3.1.7 on 2021-03-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_core', '0002_auto_20210325_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='is_biter',
            field=models.BooleanField(default=False),
        ),
    ]
