# Generated by Django 3.1.7 on 2021-03-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):


    dependencies = [
        ('dogs_core', '0003_dog_is_biter'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='favorite_toy',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
