# Generated by Django 3.1.7 on 2021-03-25 14:39

from django.db import migrations


def make_breed_names_uppercase(apps, schema_editor):
    Breed = apps.get_model('dogs_core', 'Breed')
    for breed in Breed.objects.all():
        breed.name = breed.name.upper()
        breed.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dogs_core', '0004_dog_favorite_toy'),
    ]

    operations = [
        migrations.RunPython(make_breed_names_uppercase),
        # migrations.RunSQL("update dogs_breeds db set db.name = uppercase(db.name)")
    ]
